### ISSUE TITLE
某些情况下多网卡设备中代理服务无法正常工作，申请添加 IPV4和IPV6 自动选择或指定网络接口功能。

### ISSUE THREAD

**Issue by anymov** [arloor/rust_http_proxy#10]
问题现象：
在一台多网卡设备上运行该服务时不能正确绑定IP地址进行回复。
原因分析：
我的设备有两个网卡，IPV4+IPV6两个地址，只有IPV6是公网IP。
1 代码在绑定IP地址时,使用了"0.0.0.0"。这会绑定到所有可用的IP地址上,包括IPV4和IPV6。
2 但是在实际连接其他服务器时,使用UdpSocket绑定到"0.0.0.0:0",这样会随机绑定到一个IP上。如果绑定到了非公网IP,后续连接就会失败。
3 正确的方法是:
绑定监听时仍使用"0.0.0.0",监听所有地址；
在连接客户端前,先获取本地的正确可达的公网IP地址(比如通过某个网站的API或者路由表)；
然后在连接时,将这个IP绑定到socket。
解决方法：
1 获得发送请求的客户端地址，判断是从那个网络接口或路由表路径接收到的，然后用对应的网络接口或地址进行回复。
2 提供指定网络接口的参数由用户指定最简单有效。

**Comment by xmov-vip** [comment]
访问https://api.ipify.org 会返回一个公网IPV4地址，
同样https://api6.ipify.org会返回一个公网IPV6地址，
https://api64.ipify.org会随机返回一个IPV4或IPV6地址。
https://api64.ipify.org | 98.207.254.136 or 2a00:1450:400f:80d::200e

use reqwest::Result;

async fn get_public_ip() -> Result<String> {
  let resp = reqwest::get("https://api64.ipify.org")
    .await?
    .text()
    .await?;

  Ok(resp)
}

参考一个简单折中的方法，可能还有更好的解决办法，抛砖引玉吧，仅供参考。

**Comment by anymov** [comment]
use std::process::Command;

fn local_ip() -> io::Result<String> {

  let output = Command::new("curl")
    .arg("-s")
    .arg("-X") 
    .arg("GET")
    .arg("https://api6.ipify.org")
    .output()?
    .stdout;

  let str = match String::from_utf8(output) {
    Ok(v) => v,
    Err(e) => return Err(io::Error::new(io::ErrorKind::InvalidData, e)) 
  };

  Ok(str.trim().to_string()) 
}


我单独试了一下这个方法，显示读取到了IPV6公网地址，但是代理服务还是没有正确响应。

curl -s -X GET -4 https://ifconfig.co
curl -s -X GET -6 https://ifconfig.co
curl -s -X GET https://api.ipify.org
curl -s -X GET https://api6.ipify.org

**Comment by anymov** [comment]
IPV6单独测试可以工作，可能是没有开启双协议栈监听。

IPV6单独测试修改如下：
    let addr = SocketAddr::from(([0, 0, 0, 0], port));
    改为：
    let addr = SocketAddr::from(([0, 0, 0, 0, 0, 0, 0, 0], port));
    
可以参考：
https://stackoverflow.com/questions/63742236/how-to-detect-source-address-is-ipv4-or-ipv6
    
    fn is_mapped_to_ipv6(addr: SocketAddr) -> bool {
    match addr {
        SocketAddr::V6(v6) => match v6.ip().segments() {
            // 5 * 16 `0` bits, 16 `1` bits, leftover is actual IPv4 addr
            [0, 0, 0, 0, 0, 0xFFFF, ..] => true,
            _ => false,
        },
        _ => false,
    }
}

**Comment by arloor** [comment]
最新版支持了双栈，可以试试。

核心代码：

```Rust
use socket2::{Domain, Protocol, Socket, Type};
async fn create_dual_stack_listener(port: u16) -> io::Result<TcpListener> {
    // 创建一个IPv6的socket
    let domain = Domain::IPV6;
    let socket = Socket::new(domain, Type::STREAM, Some(Protocol::TCP))?;
    #[cfg(not(windows))]
    let _ = socket.set_reuse_address(true); // 设置reuse_address以支持快速重启

    // 支持ipv4 + ipv6双栈
    socket.set_only_v6(false)?;
    // 绑定socket到地址和端口
    let addr = SocketAddr::from(([0, 0, 0, 0, 0, 0, 0, 0], port));
    socket.bind(&addr.into())?;
    socket.listen(1024)?; // 监听，128为backlog的大小

    // 将socket2::Socket转换为std::net::TcpListener
    let std_listener = std::net::TcpListener::from(socket);
    let _ = std_listener.set_nonblocking(true);

    TcpListener::from_std(std_listener)
}
```

**Comment by anymov** [comment]
**已经测试双栈版本工作正常，感谢作者的辛勤付出！！！**

测试环境：
A：多网卡IPV4+IPV6，IPV4公网+IPV6公网，测试双栈地址均可以正常代理；
B：多网卡IPV4+IPV6，IPV4内网+IPV6公网，测试IPV6地址上可以正常代理。

地址绑定：
netstat -tuln | grep 3128
tcp6       0      0 :::3128                 :::*                    LISTEN     

lsof -i:3128
COMMAND      PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
rust_http 632063 root   11u  IPv6 48251059      0t0  TCP *:3128 (LISTEN)

 ss -anp | grep 3128
tcp   LISTEN     0      1024             *:3128             *:*        users:(("rust_http_proxy",pid=632063,fd=11))
