### ISSUE TITLE
使用http2连接会出现问题

### ISSUE THREAD

**Issue by yqk100** [arloor/rust_http_proxy#18]
手机端在WLAN网络下gost/v2rayng/clash/sagernet使用http2连接rust_http_proxy的过程中切换到移动数据后连接使用10秒以上再切回WLAN网络就出现完全无法连接的情况，服务端没有任何WLAN网络IP连接的信息日志出现；如果使用https连接就没有上面情况。
广电/联通/移动都相同情况

**Comment by arloor** [comment]
不明白你说的http2是什么意思

**Comment by arloor** [comment]
没有ip连接进来的日志就是没连进来，检查网络相关的问题，估计跟这个软件没啥关系。你提的都是一样的问题，可以不提了吗？想直接关闭你的issue。但凡看得懂一点代码，就能知道，我的代码里没有魔法会造成你这种情况

**Comment by yqk100** [comment]
> 不明白你说的http2是什么意思
使用域名连接服务
客户端：
https：
https://tet.com:443
http2：
http2://tet.com:443

**Comment by arloor** [comment]
你这是什么客户端定义的url，没见过。
请用计算机术语在github上讨论。
我不会提供任何对此issue的帮助。
