### ISSUE TITLE
部署教程

### ISSUE THREAD

**Issue by qiangweihewu** [arloor/rust_http_proxy#3]
你好，谢谢开发这个项目！
尝试用自己的tls证书部署，在好几个服务器部署后显示部署成功，但客户端一直连接不上，所以怀疑是不是环境变量没设定好，或者客户端没有配置对，客户端用的是switchyomega的https代理。
所以，不知道可以提供一个更加详细的部署教程吗，比如服务器配置信息放置在一个文件里，客户端完整配置信息也由服务器打印出来
非常感谢！

**Comment by qiangweihewu** [comment]
> 你好，谢谢开发这个项目！ 尝试用自己的tls证书部署，在好几个服务器部署后显示部署成功，但客户端一直连接不上，所以怀疑是不是环境变量没设定好，或者客户端没有配置对，客户端用的是switchyomega的https代理。 所以，不知道可以提供一个更加详细的部署教程吗，比如服务器配置信息放置在一个文件里，客户端完整配置信息也由服务器打印出来 非常感谢！

刚测试小火煎是可以用的，不知道为什么switchyomega不能用

**Comment by arloor** [comment]
你是用rpm安装的还是二进制包安装的？
你的tls证书是自签发的还是ca签发的（比如acme或者免费ca）？
你的客户端用的是switchomega？

**Comment by qiangweihewu** [comment]
> 你是用rpm安装的还是二进制包安装的？ 你的tls证书是自签发的还是ca签发的（比如acme或者免费ca）？ 你的客户端用的是switchomega？

对，在switchomega不行，在小火箭可以。
用的是linux 64位可执行文件，证书是letsencrypt签发的。

**Comment by arloor** [comment]
设置环境变量ask_for_auth=true应该就可以在swithomega用了，但不建议开启，这会告诉别人这是个http代理。这个是chrome插件的机制导致的，不建议用switchomega，主流的客户端代理软件clash、surge、小火煎等都是可以作为服务端的。

相关的issue见https://github.com/FelisCatus/SwitchyOmega/issues/2169

**Comment by qiangweihewu** [comment]
> 设置环境变量ask_for_auth=true应该就可以在swithomega用了，但不建议开启，这会告诉别人这是个http代理。这个是chrome插件的机制导致的，不建议用switchomega，主流的客户端代理软件clash、surge、小火煎等都是可以作为服务端的。
> 
> 
> 
> 相关的issue见https://github.com/FelisCatus/SwitchyOmega/issues/2169

那就明白了，谢谢！
