### ISSUE TITLE
在甲骨文云中编译不通过，请帮助检查一下，谢谢。

### ISSUE THREAD

**Issue by anymov** [arloor/rust_http_proxy#9]
Compiling rust_http_proxy v0.1.1 (/root/rust_http_proxy)
error[E0446]: crate-private type `config::Config` in public interface
  --> src/proxy.rs:57:5
   |
57 | /     pub async fn proxy(
58 | |         &self,
59 | |         mut req: Request<hyper::body::Incoming>,
60 | |         proxy_config: &'static Config,
61 | |         client_socket_addr: SocketAddr,
62 | |         context: Arc<RwLock<Context>>,
63 | |     ) -> Result<Response<BoxBody<Bytes, io::Error>>, io::Error> {
   | |_______________________________________________________________^ can't leak crate-private type
   |
  ::: src/config.rs:82:1
   |
82 |   pub(crate) struct Config {
   |   ------------------------ `config::Config` declared as crate-private

error[E0446]: crate-private type `config::Config` in public interface
  --> src/web_func.rs:41:1
   |
41 | / pub async fn serve_http_request(
42 | |     req: &Request<impl Body>,
43 | |     client_socket_addr: SocketAddr,
44 | |     proxy_config: &'static Config,
...  |
48 | |     prom_registry: Arc<Registry>,
49 | | ) -> Result<Response<BoxBody<Bytes, io::Error>>, Error> {
   | |_______________________________________________________^ can't leak crate-private type
   |
  ::: src/config.rs:82:1
   |
82 |   pub(crate) struct Config {
   |   ------------------------ `config::Config` declared as crate-private

For more information about this error, try `rustc --explain E0446`.
error: could not compile `rust_http_proxy` (bin "rust_http_proxy") due to 2 previous errors

====================================================

So in src/config.rs change:

pub(crate) struct Config {
  // ...
}
To:
pub struct Config {
  // ...
}
And that should resolve the errors.

**Comment by anymov** [comment]
同时，使用过程中发现原来项目中自带的/etc/rust_http_proxy/env环境变量文件在新版本中不能很好的工作，请核对一下。

**Comment by arloor** [comment]
升级rust到最新版

新版不使用环境变量的方式了，用命令行参数

PS：竟然真有人在用这个
